import React from 'react';
import { ArchitectureDetails, AppIdea } from '../types';
import { 
  Database, Server, Layout, Copy, Check, Shield, 
  Rocket, Zap, Globe, ListTodo, Workflow, Layers,
  Calendar, Download, FolderTree, BarChart3, Users, Clock, AlertCircle, Save
} from 'lucide-react';
import { useState } from 'react';
import { Button } from './Button';
import { DiagramView } from './DiagramView';

interface ArchitectureViewProps {
  idea: AppIdea;
  architecture: ArchitectureDetails;
  onSave: () => void;
}

export const ArchitectureView: React.FC<ArchitectureViewProps> = ({ idea, architecture, onSave }) => {
  const [copied, setCopied] = useState<string | null>(null);
  const [isSaved, setIsSaved] = useState(false);

  const copyToClipboard = (text: string, section: string) => {
    navigator.clipboard.writeText(text);
    setCopied(section);
    setTimeout(() => setCopied(null), 2000);
  };

  const handleSave = () => {
    onSave();
    setIsSaved(true);
    setTimeout(() => setIsSaved(false), 2000);
  };

  const handleDownload = () => {
    const content = `# ${idea.title} - Technical Blueprint
    
## Description
${idea.description}

## 1. Project Estimation
- Total Weeks: ${architecture.projectEstimation.totalWeeks}
- Complexity: ${architecture.projectEstimation.complexityScore}/100
- Recommended Team: ${architecture.projectEstimation.teamSizeRecommendation} devs

## 2. Database Schema (Mermaid ERD)
\`\`\`mermaid
${architecture.mermaidDiagrams.erd}
\`\`\`

## 3. Core Flow (Mermaid Sequence)
\`\`\`mermaid
${architecture.mermaidDiagrams.sequence}
\`\`\`

## 4. API Endpoints
${architecture.apiEndpoints.map(e => `- ${e.method} ${e.path}: ${e.description}`).join('\n')}

## 5. Spring Boot Modules
${architecture.springBootModules.join(', ')}

## 6. React Components
${architecture.reactComponents.join(', ')}

## 7. User Stories
${architecture.userStories.join('\n- ')}

## 8. Security Strategy
${architecture.securityStrategy.join('\n- ')}

## 9. State Management
${architecture.stateManagement}

## 10. Deployment Strategy
${architecture.deploymentStrategy.join('\n- ')}

## 11. External Integrations
${architecture.externalIntegrations.join('\n- ')}

## 12. Performance Optimizations
${architecture.performanceOptimizations.join('\n- ')}

## 13. Project Structure
\`\`\`
${architecture.projectStructure}
\`\`\`

## 14. Development Roadmap
${architecture.developmentPhases.join('\n- ')}

Generated by StackIdeator AI
`;
    
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${idea.title.replace(/\s+/g, '-').toLowerCase()}-blueprint.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const renderListSection = (title: string, icon: React.ReactNode, items: string[], colorClass: string) => (
    <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden flex flex-col h-full hover:border-slate-700 transition-colors">
      <div className="bg-slate-800/80 px-4 py-3 border-b border-slate-700 flex items-center gap-2">
        <span className={colorClass}>{icon}</span>
        <span className="font-semibold text-slate-200 text-sm">{title}</span>
      </div>
      <div className="p-4 flex-1">
        <ul className="space-y-2">
          {items.map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-300">
              <span className={`mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0 ${colorClass.replace('text-', 'bg-')}`}></span>
              <span className="leading-relaxed">{item}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );

  return (
    <div className="space-y-6 animate-fade-in-up">
      <div className="bg-gradient-to-r from-slate-800 to-slate-900 border border-slate-700 rounded-xl p-6 shadow-lg relative overflow-hidden">
        <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div>
            <div className="flex items-center gap-2 text-indigo-400 mb-2">
              <Layers className="w-5 h-5" />
              <span className="text-xs font-bold uppercase tracking-widest">Full-Stack Blueprint</span>
            </div>
            <h2 className="text-2xl font-bold text-white mb-2">{idea.title}</h2>
            <p className="text-slate-400 max-w-2xl">Comprehensive technical architecture analysis & roadmap.</p>
          </div>
          <div className="flex gap-2 flex-shrink-0">
            <Button onClick={handleSave} variant="secondary" className="flex-shrink-0">
               {isSaved ? <Check className="w-4 h-4 mr-2" /> : <Save className="w-4 h-4 mr-2" />}
               {isSaved ? 'Saved!' : 'Save Project'}
            </Button>
            <Button onClick={handleDownload} variant="outline" className="flex-shrink-0">
               <Download className="w-4 h-4 mr-2" /> Export
            </Button>
          </div>
        </div>
        <div className="absolute top-0 right-0 p-8 opacity-5">
          <Layers className="w-64 h-64 text-white" />
        </div>
      </div>

      {/* Analytics Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 flex items-center gap-4">
            <div className="bg-indigo-900/30 p-3 rounded-lg border border-indigo-500/30">
                <Clock className="w-6 h-6 text-indigo-400" />
            </div>
            <div>
                <p className="text-slate-400 text-xs font-bold uppercase tracking-wider">Est. Time to MVP</p>
                <p className="text-2xl font-bold text-white">{architecture.projectEstimation.totalWeeks} Weeks</p>
            </div>
        </div>
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 flex items-center gap-4">
            <div className="bg-emerald-900/30 p-3 rounded-lg border border-emerald-500/30">
                <Users className="w-6 h-6 text-emerald-400" />
            </div>
            <div>
                <p className="text-slate-400 text-xs font-bold uppercase tracking-wider">Team Size</p>
                <p className="text-2xl font-bold text-white">{architecture.projectEstimation.teamSizeRecommendation} Developers</p>
            </div>
        </div>
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 flex items-center gap-4">
            <div className={`p-3 rounded-lg border ${
                architecture.projectEstimation.complexityScore > 75 ? 'bg-red-900/30 border-red-500/30' : 
                architecture.projectEstimation.complexityScore > 40 ? 'bg-orange-900/30 border-orange-500/30' : 
                'bg-green-900/30 border-green-500/30'
            }`}>
                <BarChart3 className={`w-6 h-6 ${
                    architecture.projectEstimation.complexityScore > 75 ? 'text-red-400' : 
                    architecture.projectEstimation.complexityScore > 40 ? 'text-orange-400' : 
                    'text-green-400'
                }`} />
            </div>
            <div className="flex-1">
                <p className="text-slate-400 text-xs font-bold uppercase tracking-wider mb-1">Complexity Score</p>
                <div className="flex items-center gap-3">
                    <div className="h-2 flex-1 bg-slate-800 rounded-full overflow-hidden">
                        <div 
                            className={`h-full rounded-full ${
                                architecture.projectEstimation.complexityScore > 75 ? 'bg-red-500' : 
                                architecture.projectEstimation.complexityScore > 40 ? 'bg-orange-500' : 
                                'bg-green-500'
                            }`}
                            style={{ width: `${architecture.projectEstimation.complexityScore}%` }}
                        />
                    </div>
                    <span className="text-lg font-bold text-white">{architecture.projectEstimation.complexityScore}/100</span>
                </div>
            </div>
        </div>
      </div>

      {/* Visual Diagrams Section */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <DiagramView 
            code={architecture.mermaidDiagrams.erd} 
            title="Entity Relationship Diagram (ERD)" 
          />
          <DiagramView 
            code={architecture.mermaidDiagrams.sequence} 
            title="Core User Flow Sequence" 
          />
      </div>

      {/* Main 3 Columns: Backend, Frontend, User Stories */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {/* Backend */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden flex flex-col">
          <div className="bg-slate-800/80 px-4 py-3 border-b border-slate-700 flex items-center gap-2">
            <Server className="w-4 h-4 text-emerald-400" />
            <span className="font-semibold text-slate-200">Backend Architecture</span>
          </div>
          <div className="p-4 space-y-4">
            <div>
              <h4 className="text-xs uppercase text-slate-500 font-bold mb-2 tracking-wider">Spring Boot Modules</h4>
              <div className="flex flex-wrap gap-2">
                {architecture.springBootModules.map((mod, i) => (
                  <span key={i} className="text-xs text-emerald-300 bg-emerald-900/20 px-2 py-1 rounded border border-emerald-900/30 font-mono">
                    {mod}
                  </span>
                ))}
              </div>
            </div>
            <div>
               <h4 className="text-xs uppercase text-slate-500 font-bold mb-2 tracking-wider">Core Endpoints</h4>
               <div className="space-y-1.5">
                 {architecture.apiEndpoints.slice(0, 4).map((ep, i) => (
                   <div key={i} className="flex gap-2 text-xs font-mono items-center">
                     <span className={`px-1.5 py-0.5 rounded-[4px] text-[10px] font-bold min-w-[35px] text-center ${
                       ep.method === 'GET' ? 'bg-blue-500/10 text-blue-400' : 
                       ep.method === 'POST' ? 'bg-green-500/10 text-green-400' :
                       ep.method === 'DELETE' ? 'bg-red-500/10 text-red-400' : 'bg-orange-500/10 text-orange-400'
                     }`}>
                       {ep.method}
                     </span>
                     <span className="text-slate-300 truncate">{ep.path}</span>
                   </div>
                 ))}
               </div>
            </div>
          </div>
        </div>

        {/* Frontend */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden flex flex-col">
          <div className="bg-slate-800/80 px-4 py-3 border-b border-slate-700 flex items-center gap-2">
            <Layout className="w-4 h-4 text-sky-400" />
            <span className="font-semibold text-slate-200">Frontend Architecture</span>
          </div>
          <div className="p-4 space-y-4">
             <div>
               <h4 className="text-xs uppercase text-slate-500 font-bold mb-2 tracking-wider">State Management</h4>
               <p className="text-sm text-sky-200">{architecture.stateManagement}</p>
             </div>
             <div>
              <h4 className="text-xs uppercase text-slate-500 font-bold mb-2 tracking-wider">Key Components</h4>
              <div className="space-y-1">
                {architecture.reactComponents.slice(0, 6).map((comp, i) => (
                  <div key={i} className="flex items-center gap-2 text-sm text-sky-200/80">
                    <span className="w-1 h-1 rounded-full bg-sky-500"></span>
                    {comp}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* User Stories */}
        {renderListSection(
          "User Stories & Flows", 
          <ListTodo className="w-4 h-4" />, 
          architecture.userStories.slice(0, 5), 
          "text-purple-400"
        )}
      </div>

      {/* Database Schema Text */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
        <div className="bg-slate-800/80 px-4 py-3 border-b border-slate-700 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Database className="w-4 h-4 text-indigo-400" />
            <span className="font-semibold text-slate-200">Database Schema (SQL View)</span>
          </div>
          <button 
            onClick={() => copyToClipboard(architecture.databaseSchema, 'db')}
            className="text-xs flex items-center gap-1 text-slate-400 hover:text-white transition-colors"
          >
            {copied === 'db' ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
            {copied === 'db' ? 'Copied' : 'Copy SQL'}
          </button>
        </div>
        <div className="p-4 bg-black/30">
          <pre className="text-xs md:text-sm font-mono text-slate-300 overflow-x-auto whitespace-pre-wrap max-h-48 scrollbar-thin">
            {architecture.databaseSchema}
          </pre>
        </div>
      </div>

      {/* Project Structure Section */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
        <div className="bg-slate-800/80 px-4 py-3 border-b border-slate-700 flex items-center justify-between">
            <div className="flex items-center gap-2">
                <FolderTree className="w-4 h-4 text-amber-400" />
                <span className="font-semibold text-slate-200">Monorepo Folder Structure</span>
            </div>
            <button 
                onClick={() => copyToClipboard(architecture.projectStructure, 'structure')}
                className="text-xs flex items-center gap-1 text-slate-400 hover:text-white transition-colors"
            >
                {copied === 'structure' ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
                {copied === 'structure' ? 'Copied' : 'Copy Tree'}
            </button>
        </div>
        <div className="p-4 bg-black/30">
            <pre className="text-xs font-mono text-amber-100/80 overflow-x-auto whitespace-pre max-h-64 scrollbar-thin leading-snug">
                {architecture.projectStructure}
            </pre>
        </div>
      </div>

      {/* Feature Grids */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {renderListSection(
          "Security Strategy", 
          <Shield className="w-4 h-4" />, 
          architecture.securityStrategy, 
          "text-red-400"
        )}

        {renderListSection(
          "DevOps & Deployment", 
          <Rocket className="w-4 h-4" />, 
          architecture.deploymentStrategy, 
          "text-orange-400"
        )}

        {renderListSection(
          "External Integrations", 
          <Globe className="w-4 h-4" />, 
          architecture.externalIntegrations, 
          "text-blue-400"
        )}

        {renderListSection(
          "Performance Strategy", 
          <Zap className="w-4 h-4" />, 
          architecture.performanceOptimizations, 
          "text-yellow-400"
        )}
        
        {/* Development Roadmap */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden flex flex-col md:col-span-2 lg:col-span-2">
            <div className="bg-slate-800/80 px-4 py-3 border-b border-slate-700 flex items-center gap-2">
                <Calendar className="w-4 h-4 text-pink-400" />
                <span className="font-semibold text-slate-200">Development Roadmap</span>
            </div>
            <div className="p-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-4">
                    {architecture.developmentPhases.map((phase, i) => (
                        <div key={i} className="flex items-start gap-3">
                            <div className="flex-shrink-0 w-6 h-6 rounded-full bg-pink-500/10 border border-pink-500/30 flex items-center justify-center text-xs font-bold text-pink-400 mt-0.5">
                                {i + 1}
                            </div>
                            <p className="text-sm text-slate-300 leading-relaxed pt-0.5">{phase}</p>
                        </div>
                    ))}
                </div>
            </div>
        </div>
      </div>
    </div>
  );
};