import React from 'react';
import { ArchitectureDetails, AppIdea } from '../types';
import { 
  Database, Server, Layout, Copy, Check, Shield, 
  Rocket, Zap, Globe, ListTodo, Workflow, Layers 
} from 'lucide-react';
import { useState } from 'react';

interface ArchitectureViewProps {
  idea: AppIdea;
  architecture: ArchitectureDetails;
}

export const ArchitectureView: React.FC<ArchitectureViewProps> = ({ idea, architecture }) => {
  const [copied, setCopied] = useState<string | null>(null);

  const copyToClipboard = (text: string, section: string) => {
    navigator.clipboard.writeText(text);
    setCopied(section);
    setTimeout(() => setCopied(null), 2000);
  };

  const renderListSection = (title: string, icon: React.ReactNode, items: string[], colorClass: string) => (
    <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden flex flex-col h-full hover:border-slate-700 transition-colors">
      <div className="bg-slate-800/80 px-4 py-3 border-b border-slate-700 flex items-center gap-2">
        <span className={colorClass}>{icon}</span>
        <span className="font-semibold text-slate-200 text-sm">{title}</span>
      </div>
      <div className="p-4 flex-1">
        <ul className="space-y-2">
          {items.map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-300">
              <span className={`mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0 ${colorClass.replace('text-', 'bg-')}`}></span>
              <span className="leading-relaxed">{item}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );

  return (
    <div className="space-y-6 animate-fade-in-up">
      <div className="bg-gradient-to-r from-slate-800 to-slate-900 border border-slate-700 rounded-xl p-6 shadow-lg relative overflow-hidden">
        <div className="relative z-10">
          <div className="flex items-center gap-2 text-indigo-400 mb-2">
            <Layers className="w-5 h-5" />
            <span className="text-xs font-bold uppercase tracking-widest">Full-Stack Blueprint</span>
          </div>
          <h2 className="text-2xl font-bold text-white mb-2">{idea.title}</h2>
          <p className="text-slate-400 max-w-2xl">Comprehensive 10-point technical architecture analysis generated by Gemini 2.5.</p>
        </div>
        <div className="absolute top-0 right-0 p-8 opacity-5">
          <Layers className="w-64 h-64 text-white" />
        </div>
      </div>

      {/* Main 3 Columns: Backend, Frontend, User Stories */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {/* Backend */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden flex flex-col">
          <div className="bg-slate-800/80 px-4 py-3 border-b border-slate-700 flex items-center gap-2">
            <Server className="w-4 h-4 text-emerald-400" />
            <span className="font-semibold text-slate-200">1. Spring Boot Backend</span>
          </div>
          <div className="p-4 space-y-4">
            <div>
              <h4 className="text-xs uppercase text-slate-500 font-bold mb-2 tracking-wider">Modules</h4>
              <div className="flex flex-wrap gap-2">
                {architecture.springBootModules.map((mod, i) => (
                  <span key={i} className="text-xs text-emerald-300 bg-emerald-900/20 px-2 py-1 rounded border border-emerald-900/30 font-mono">
                    {mod}
                  </span>
                ))}
              </div>
            </div>
            <div>
               <h4 className="text-xs uppercase text-slate-500 font-bold mb-2 tracking-wider">Core Endpoints</h4>
               <div className="space-y-1.5">
                 {architecture.apiEndpoints.slice(0, 4).map((ep, i) => (
                   <div key={i} className="flex gap-2 text-xs font-mono items-center">
                     <span className={`px-1.5 py-0.5 rounded-[4px] text-[10px] font-bold min-w-[35px] text-center ${
                       ep.method === 'GET' ? 'bg-blue-500/10 text-blue-400' : 
                       ep.method === 'POST' ? 'bg-green-500/10 text-green-400' :
                       ep.method === 'DELETE' ? 'bg-red-500/10 text-red-400' : 'bg-orange-500/10 text-orange-400'
                     }`}>
                       {ep.method}
                     </span>
                     <span className="text-slate-300 truncate">{ep.path}</span>
                   </div>
                 ))}
               </div>
            </div>
          </div>
        </div>

        {/* Frontend */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden flex flex-col">
          <div className="bg-slate-800/80 px-4 py-3 border-b border-slate-700 flex items-center gap-2">
            <Layout className="w-4 h-4 text-sky-400" />
            <span className="font-semibold text-slate-200">2. React Frontend</span>
          </div>
          <div className="p-4 space-y-4">
             <div>
               <h4 className="text-xs uppercase text-slate-500 font-bold mb-2 tracking-wider">State Management</h4>
               <p className="text-sm text-sky-200">{architecture.stateManagement}</p>
             </div>
             <div>
              <h4 className="text-xs uppercase text-slate-500 font-bold mb-2 tracking-wider">Key Components</h4>
              <div className="space-y-1">
                {architecture.reactComponents.slice(0, 6).map((comp, i) => (
                  <div key={i} className="flex items-center gap-2 text-sm text-sky-200/80">
                    <span className="w-1 h-1 rounded-full bg-sky-500"></span>
                    {comp}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* User Stories */}
        {renderListSection(
          "3. User Stories & Flows", 
          <ListTodo className="w-4 h-4" />, 
          architecture.userStories.slice(0, 5), 
          "text-purple-400"
        )}
      </div>

      {/* Database Full Width */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
        <div className="bg-slate-800/80 px-4 py-3 border-b border-slate-700 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Database className="w-4 h-4 text-indigo-400" />
            <span className="font-semibold text-slate-200">4. Database Schema</span>
          </div>
          <button 
            onClick={() => copyToClipboard(architecture.databaseSchema, 'db')}
            className="text-xs flex items-center gap-1 text-slate-400 hover:text-white transition-colors"
          >
            {copied === 'db' ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
            {copied === 'db' ? 'Copied' : 'Copy SQL'}
          </button>
        </div>
        <div className="p-4 bg-black/30">
          <pre className="text-xs md:text-sm font-mono text-slate-300 overflow-x-auto whitespace-pre-wrap max-h-48 scrollbar-thin">
            {architecture.databaseSchema}
          </pre>
        </div>
      </div>

      {/* 6 Remaining Feature Grids */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {renderListSection(
          "5. Security Strategy", 
          <Shield className="w-4 h-4" />, 
          architecture.securityStrategy, 
          "text-red-400"
        )}

        {renderListSection(
          "6. DevOps & Deployment", 
          <Rocket className="w-4 h-4" />, 
          architecture.deploymentStrategy, 
          "text-orange-400"
        )}

        {renderListSection(
          "7. External Integrations", 
          <Globe className="w-4 h-4" />, 
          architecture.externalIntegrations, 
          "text-blue-400"
        )}

        {renderListSection(
          "8. Performance", 
          <Zap className="w-4 h-4" />, 
          architecture.performanceOptimizations, 
          "text-yellow-400"
        )}
        
        {/* Placeholder for remaining 2 items concept if needed, or just expanding lists */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden flex flex-col md:col-span-2 lg:col-span-2">
            <div className="bg-slate-800/80 px-4 py-3 border-b border-slate-700 flex items-center gap-2">
                <Workflow className="w-4 h-4 text-teal-400" />
                <span className="font-semibold text-slate-200">9 & 10. API Structure Detail</span>
            </div>
            <div className="p-4 grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                    <h4 className="text-xs text-slate-500 font-bold mb-2 uppercase">REST Standards</h4>
                    <p className="text-sm text-slate-300">
                        All endpoints follow standard RESTful conventions. 
                        Use JSON for request/response bodies. 
                        Implement standard HTTP status codes (200, 201, 400, 401, 404, 500).
                    </p>
                </div>
                 <div>
                    <h4 className="text-xs text-slate-500 font-bold mb-2 uppercase">Error Handling</h4>
                    <p className="text-sm text-slate-300">
                        Global Exception Handler (`@ControllerAdvice`) configured to return standardized `ApiError` objects containing timestamp, status, and debug message.
                    </p>
                </div>
            </div>
        </div>
      </div>
    </div>
  );
};